title: MITBBS Stock Digest
description: Daily digest of stock & investment discussions from newmitbbs.com
baseurl: "/mitbbs-stock-digest-site"
url: "https://ixnix.github.io"
theme: minima
markdown: kramdown
permalink: /digests/:year/:month/:day/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
