title: 股海弄潮 每日摘要
description: Daily digest of stock & investment discussions from newmitbbs.com
baseurl: ""
url: "https://ixnix.github.io/mitbbs-stock-digest-site"
theme: minima
markdown: kramdown
permalink: /digests/:year-:month-:day/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
